info:
  description: used for managing messages

# Spring properties
spring:
  application:
      name: messaging-service
  datasource:
      username: RevatureMessaging
      password: pazzword
      url: ${url}
      driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
      database-platform: org.hibernate.dialect.Oracle10gDialect

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8082  # HTTP (Tomcat) port
