# Spring properties
spring:
  application:
     name: messaging-service
   datasource:
        username: RevatureMessaging
        password: pazzword
        url: {url}
        driver-class-name: oracle.jdbc.driver.OracleDriver

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8081  # HTTP (Tomcat) port
